### ISSUE TITLE
Setting to change RearmTicks

### ISSUE THREAD

**Issue by kotomaran** [Dorely/RimworldBetaTraps#1]
https://github.com/Dorely/RimworldBetaTraps/blob/46e2c27650b71ba223b2d1f1305ae8d408df8f1d/Source/AI/JobDriver_RearmTraps.cs#L13
This value being configurable would be appreciated.
If the mod won't be updated any soon, maybe you could advise me if I can change it somehow through XML without compiling the whole thing?

**Comment by Dorely** [comment]
Going to push an update to add this setting tonight. Thanks for the idea!
