### ISSUE TITLE
Trap deal no dmg

### ISSUE THREAD

**Issue by taza325** [Dorely/RimworldBetaTraps#2]
Trap as in title deal no dmg to enemies with or without armor pls could u fix it.

**Comment by Dorely** [comment]
If you could provide a list of all mods that you have loaded I will investigate - It should be noted that it is usually working, so this is most likely a mod conflict

**Comment by taza325** [comment]
My modlist:
brrainz.harmony
xell.moretradeships.patched
ludeon.rimworld
unlimitedhugs.hugslib
dorely.betatraps
jaxxa.ed.enhancedoptions
hatti.cleaningarea
pyrce.modlist
ogliss.toastehs.veinminer
twistedpacifist.reasonablecomponents
paradox.morevanillaturrets
legodude17.smartdecon
zzz.invisibleconduit
ratys.rtsolarflareshield
jkluch.haultostack
ludeon.rimworld.ideology
caesarv6.damageindicators
madeline.modmismatchformatter
falconne.aff
nanoce.glasslights
ludeon.rimworld.ideology
sr.modrimworld.factionalwar
fluffy.modmanager
mlie.morefactioninteraction
mlie.sdadvancedpowergeneration
unlimitedhugs.allowtool
erdelf.humanoidalienraces
fluffy.animaltab
automatic.bionicicons
owlchemist.bettervanillamasking
oskarpotocki.vanillafactionsexpanded.core
vanillaexpanded.varme
vanillaexpanded.vwe
ceteam.combatextended
atlas.androidtiers
unlimitedhugs.defensivepositions
tikubonn.dontblockdoor
dracoix.doormat.r12a
cp.rimmunation.2.security
cp.rimmunation.2.weapons
cp.rimmunation.2.clothing
frozensnowfox.filthvanisheswithrainandtime
roolo.giddyupcore
orion.hospitality
arandomkiwi.huntforme
taveron.increasedstack
jaxe.bubbles
ratys.madskills
unlimitedhugs.mapreroll
fluffy.medicaltab
spoonshortage.adogsaidanimalprosthetics
spino.megafauna
erdelf.minifyeverything
telkir.tmods.morefloors
extracting.organs
hatti.qualitybuilder
ogliss.thewhitecrayon.quarry
automatic.recipeicons
dubwise.rimatomics
dubwise.rimefeller
rimfridge.kv.rw
ratys.rtfuse
aoba.tent
ceteam.combatextendedarmors
ykara.epoe
edb.preparecarefully
arandomkiwi.rimsaves
jaxe.rimhud
uuugggg.replacestuff
dubwise.dubsskylights
vanillaexpanded.vfeart
smashphil.neceros.srtsexpanded
marvinkosh.sometimesraidsgowrong
uuugggg.sharetheload
jecrell.doorsexpanded
syrchalis.setupcamp
rimsenal.evp
haplo.miscellaneous.robots
fluffy.fluffyrelations
mehni.pickupandhaul
notfood.mendandrecycle
falconne.heatmap
thewirelord354.conduitdeconstruct
trasheddt.industrialisation
fluffy.blueprints
chjees.androids
roolo.runandgun
kentington.saveourship2
petetimessix.simplesidearms
dhultgren.smarterconstruction
gt.sam.tilledsoil
crashm.colorcodedmoodbar.11
com.github.alandariva.moreplanning
vinalx.researchpalforked
tradingspot.kv.rw
vanillaexpanded.vaecd
vanillaexpanded.vfecore
vanillaexpanded.vfefarming
vanillaexpanded.vfemedical
vanillaexpanded.vfepower
4loris4.morelinkables
vanillaexpanded.vfeproduction
vanillaexpanded.vfesecurity
vanillaexpanded.vplantse
fluffy.worktab
carnysenpai.enableoversizedweapons
targhetti.showdrafteesweapon
vanillaexpanded.vappe
vanillaexpanded.vfespacer
vanillaexpanded.vhe
won.hair
won2.hair
mlie.roadsoftherim
owlchemist.undergroundpowerconduits
